%{?scl:%scl_package perl-Data-Integer}
%{!?scl:%global pkg_name %{name}}

Name:           %{?scl_prefix}perl-Data-Integer
Version:        0.005
Release:        2%{?dist}
Summary:        Details of the native integer data type
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Data-Integer/
Source0:        http://www.cpan.org/authors/id/Z/ZE/ZEFRAM/Data-Integer-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{pkg_name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
%{?scl:Requires: %{scl}-runtime}
BuildRequires:  %{?scl_prefix}perl >= 0:5.006
BuildRequires:  %{?scl_prefix}perl(Carp)
BuildRequires:  %{?scl_prefix}perl(constant)
BuildRequires:  %{?scl_prefix}perl(Exporter)
BuildRequires:  %{?scl_prefix}perl(integer)
BuildRequires:  %{?scl_prefix}perl(Module::Build)
BuildRequires:  %{?scl_prefix}perl(parent)
BuildRequires:  %{?scl_prefix}perl(strict)
BuildRequires:  %{?scl_prefix}perl(Test::More)
BuildRequires:  %{?scl_prefix}perl(warnings)
Requires:       %{?scl_prefix}perl(Carp)
Requires:       %{?scl_prefix}perl(constant)
Requires:       %{?scl_prefix}perl(Exporter)
Requires:       %{?scl_prefix}perl(integer)
Requires:       %{?scl_prefix}perl(parent)
Requires:       %{?scl_prefix}perl(strict)
Requires:       %{?scl_prefix}perl(warnings)
Requires:       %{?scl_prefix}perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
This module is about the native integer numerical data type. A native
integer is one of the types of datum that can appear in the numeric part
of a Perl scalar. This module supplies constants describing the native
integer type.

%prep
%setup -q -n Data-Integer-%{version}

%build
%{?scl:scl enable %{scl} - << \EOF}
%{__perl} Build.PL installdirs=vendor
%{?scl:EOF}
%{?scl:scl enable %{scl} - << \EOF}
./Build
%{?scl:EOF}

%install
rm -rf $RPM_BUILD_ROOT

%{?scl:scl enable %{scl} - << \EOF}
./Build install destdir=$RPM_BUILD_ROOT create_packlist=0
%{?scl:EOF}
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
%{?scl:scl enable %{scl} - << \EOF}
./Build test
%{?scl:EOF}

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes META.json README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Wed Jan 11 2017 Doran L. Barton <fozz@iodynamics.com> 0.005-2
- new package built with tito

* Wed Jan 11 2017 Doran L. Barton <doran@bluehost.com> 0.005-1
- Specfile autogenerated by cpanspec 1.78.