%{?scl:%scl_package perl-File-Remove}
%{!?scl:%global pkg_name %{name}}

Name:           %{?scl_prefix}perl-File-Remove
Version:        1.57
Release:        2%{?dist}
Summary:        Remove files and directories
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/File-Remove/
Source0:        http://www.cpan.org/authors/id/S/SH/SHLOMIF/File-Remove-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{pkg_name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
%{?scl:Requires: %{scl}-runtime}
BuildRequires:  %{?scl_prefix}perl >= 0:5.006
BuildRequires:  %{?scl_prefix}perl(constant)
BuildRequires:  %{?scl_prefix}perl(Cwd) >= 3.29
BuildRequires:  %{?scl_prefix}perl(ExtUtils::MakeMaker)
BuildRequires:  %{?scl_prefix}perl(File::Path)
BuildRequires:  %{?scl_prefix}perl(File::Spec) >= 3.29
BuildRequires:  %{?scl_prefix}perl(File::Spec::Functions)
BuildRequires:  %{?scl_prefix}perl(File::Temp)
BuildRequires:  %{?scl_prefix}perl(IO::Handle)
BuildRequires:  %{?scl_prefix}perl(strict)
BuildRequires:  %{?scl_prefix}perl(Test::More)
BuildRequires:  %{?scl_prefix}perl(warnings)
Requires:       %{?scl_prefix}perl(constant)
Requires:       %{?scl_prefix}perl(Cwd) >= 3.29
Requires:       %{?scl_prefix}perl(File::Path)
Requires:       %{?scl_prefix}perl(File::Spec) >= 3.29
Requires:       %{?scl_prefix}perl(strict)
Requires:       %{?scl_prefix}perl(warnings)
Requires:       %{?scl_prefix}perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
File::Remove::remove removes files and directories. It acts like /bin/rm,
for the most part. Although unlink can be given a list of files, it will
not remove directories; this module remedies that. It also accepts
wildcards, * and ?, as arguments for filenames.

%prep
%setup -q -n File-Remove-%{version}

%build
%{?scl:scl enable %{scl} - << \EOF}
%{__perl} Makefile.PL INSTALLDIRS=vendor
%{?scl:EOF}
%{?scl:scl enable %{scl} - << \EOF}
make %{?_smp_mflags}
%{?scl:EOF}


%install
rm -rf $RPM_BUILD_ROOT

%{?scl:scl enable %{scl} - << \EOF}
make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT
%{?scl:EOF}

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
%{?scl:scl enable %{scl} - << \EOF}
make test
%{?scl:EOF}


%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes dist.ini LICENSE README weaver.ini
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Thu Jan 12 2017 Doran L. Barton <fozz@iodynamics.com> 1.57-2
- new package built with tito

* Thu Jan 12 2017 Doran L. Barton <doran@bluehost.com> 1.57-1
- Specfile autogenerated by cpanspec 1.78.